using Microsoft.Extensions.Logging.Abstractions;
using Npgsql;
using Ouroboros.BuildingBlocks.Application;
using Testcontainers.PostgreSql;

namespace Ouroboros.BuildingBlocks.Infrastructure.Tests.Services;

// Cada teste sobe seu próprio Postgres efêmero: o cenário de concorrência precisa de duas conexões
// reais competindo pela mesma linha, o que não dá pra simular direito compartilhando estado entre
// testes.
[Trait("Category", "Integration")]
public sealed class OutboxPublisherServiceTests : IAsyncLifetime
{
	private readonly PostgreSqlContainer _container = new PostgreSqlBuilder("postgres:17")
		.Build();

	private NpgsqlConnectionFactory _connectionFactory = null!;
	private NpgsqlConnection _seedConnection = null!;

	public async Task InitializeAsync()
	{
		await _container.StartAsync();

		_seedConnection = new NpgsqlConnection(_container.GetConnectionString());
		await _seedConnection.OpenAsync();

		await using (var command = new NpgsqlCommand(
			"""
			CREATE SCHEMA IF NOT EXISTS common;

			CREATE TABLE common.outbox_messages
			(
			    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			    external_id uuid NOT NULL,
			    created_at timestamp with time zone NOT NULL,
			    updated_at timestamp with time zone NULL,
			    message_type text NOT NULL,
			    schema_version integer NOT NULL,
			    producer text NOT NULL,
			    payload text NOT NULL,
			    correlation_id text NULL,
			    status integer NOT NULL,
			    published_at timestamp with time zone NULL,
			    attempt_count integer NOT NULL,
			    last_attempt_at timestamp with time zone NULL,
			    next_attempt_at timestamp with time zone NULL,
			    last_error text NULL
			);
			""",
			_seedConnection))
		{
			await command.ExecuteNonQueryAsync();
		}

		_connectionFactory = new NpgsqlConnectionFactory(_container.GetConnectionString());
	}

	public async Task DisposeAsync()
	{
		await _connectionFactory.DisposeAsync();
		await _seedConnection.DisposeAsync();
		await _container.DisposeAsync();
	}

	[Fact]
	public async Task PublishPendingAsync_publishes_a_pending_message_and_marks_it_as_published()
	{
		var messageType = $"tipo_{Guid.NewGuid():N}";
		await SeedPendingMessageAsync(messageType);
		var publisher = new FakeMessagePublisher();
		var service = NewService(publisher);

		var publishedCount = await service.PublishPendingAsync(CancellationToken.None);
		var pendingAfter = await service.PublishPendingAsync(CancellationToken.None);

		Assert.Equal(1, publishedCount);
		Assert.Equal(0, pendingAfter);
		Assert.Single(publisher.PublishedEnvelopes);
		Assert.Equal(messageType, publisher.PublishedEnvelopes[0].MessageType);
	}

	[Fact]
	public async Task PublishPendingAsync_registers_a_failed_attempt_and_schedules_a_retry_when_the_publisher_throws()
	{
		var messageType = $"tipo_{Guid.NewGuid():N}";
		await SeedPendingMessageAsync(messageType);
		var publisher = new FakeMessagePublisher { FailingMessageType = messageType };
		var service = NewService(publisher, initialRetryDelay: TimeSpan.FromHours(1));

		var processedCount = await service.PublishPendingAsync(CancellationToken.None);
		var pendingRightAfter = await service.PublishPendingAsync(CancellationToken.None);

		Assert.Equal(1, processedCount);
		// Não fica pendente de novo imediatamente: RegisterFailedAttempt agendou a próxima tentativa
		// para daqui a uma hora, então a segunda varredura não deve pegar essa mensagem agora.
		Assert.Equal(0, pendingRightAfter);

		var (status, attemptCount, lastError, nextAttemptAt) = await ReadMessageStateAsync(messageType);
		Assert.Equal(0, status); // OutboxMessageStatus.Pending — continua pendente, só adiada.
		Assert.Equal(1, attemptCount);
		Assert.NotNull(lastError);
		Assert.NotNull(nextAttemptAt);
		Assert.True(nextAttemptAt > DateTime.UtcNow);
	}

	[Fact]
	public async Task PublishPendingAsync_does_not_publish_the_same_message_twice_when_two_instances_run_concurrently()
	{
		var messageType = $"tipo_{Guid.NewGuid():N}";
		await SeedPendingMessageAsync(messageType);
		var publisher = new CountingMessagePublisher();
		var firstInstance = NewService(publisher);
		var secondInstance = NewService(publisher);

		var results = await Task.WhenAll(
			firstInstance.PublishPendingAsync(CancellationToken.None),
			secondInstance.PublishPendingAsync(CancellationToken.None));

		Assert.Equal(1, results.Sum());
		Assert.Equal(1, publisher.PublishCount);
	}

	private OutboxPublisherService NewService(
		IMessagePublisher publisher,
		TimeSpan? initialRetryDelay = null)
	{
		var options = new OutboxOptions(
			PollingInterval: TimeSpan.FromSeconds(30),
			BatchSize: 10,
			InitialRetryDelay: initialRetryDelay ?? TimeSpan.FromSeconds(30),
			MaxRetryDelay: TimeSpan.FromMinutes(5)
		);

		return new OutboxPublisherService(
			session: new DbSession(_connectionFactory),
			publisher: publisher,
			options: options,
			logger: NullLogger<OutboxPublisherService>.Instance
		);
	}

	private async Task SeedPendingMessageAsync(string messageType)
	{
		await using var session = new DbSession(_connectionFactory);
		var queue = new OutboxMessageQueueService(
			session,
			new FakeCorrelationIdAccessor(),
			new OutboxProducer("teste"));

		await session.BeginTransactionAsync(CancellationToken.None);
		queue.Add(messageType, schemaVersion: 1, payload: new { });
		await session.FlushAsync(CancellationToken.None);
		await session.CommitAsync(CancellationToken.None);
	}

	private async Task<(int Status, int AttemptCount, string? LastError, DateTime? NextAttemptAt)> ReadMessageStateAsync(
		string messageType)
	{
		await using var command = new NpgsqlCommand(
			"""
			SELECT
				status,
				attempt_count,
				last_error,
				next_attempt_at
			FROM
				common.outbox_messages
			WHERE
				message_type = @message_type;
			""",
			_seedConnection);
		command.Parameters.AddWithValue("message_type", messageType);

		await using var reader = await command.ExecuteReaderAsync();
		await reader.ReadAsync();

		return (
			reader.GetInt32(0),
			reader.GetInt32(1),
			reader.IsDBNull(2) ? null : reader.GetString(2),
			reader.IsDBNull(3) ? null : reader.GetDateTime(3));
	}

	private sealed class CountingMessagePublisher : IMessagePublisher
	{
		private int _publishCount;

		public int PublishCount => _publishCount;

		public Task PublishAsync(MessageEnvelope envelope, CancellationToken cancellationToken)
		{
			Interlocked.Increment(ref _publishCount);
			return Task.CompletedTask;
		}
	}
}
