CREATE TABLE auth.refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz,
    user_id bigint NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);

CREATE UNIQUE INDEX refresh_tokens_external_id_key ON auth.refresh_tokens (external_id);
CREATE UNIQUE INDEX refresh_tokens_token_hash_key ON auth.refresh_tokens (token_hash);
CREATE INDEX refresh_tokens_user_id_idx ON auth.refresh_tokens (user_id);
