CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE auth.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz,
    login text NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    email_confirmed boolean NOT NULL,
    password_hash text NOT NULL,
    password_changed_at timestamptz NOT NULL,
    active boolean NOT NULL,
    last_login_at timestamptz
);

CREATE UNIQUE INDEX users_external_id_key ON auth.users (external_id);
CREATE UNIQUE INDEX users_login_key ON auth.users (login);
CREATE UNIQUE INDEX users_email_key ON auth.users (email);
