CREATE TABLE auth.tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz,
    user_id bigint NOT NULL,
    type text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    CONSTRAINT tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);

CREATE UNIQUE INDEX tokens_external_id_key ON auth.tokens (external_id);
CREATE UNIQUE INDEX tokens_token_hash_key ON auth.tokens (token_hash);
CREATE INDEX tokens_user_id_idx ON auth.tokens (user_id);
