<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ouroboros.Modules.Auth.Domain\Ouroboros.Modules.Auth.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Ouroboros.Common.Application\Ouroboros.Common.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
