DROP TABLE common.email_messages;

ALTER TABLE auth.tokens
    DROP COLUMN email_message_id;

ALTER TABLE auth.tokens
    ADD COLUMN notification_request_id uuid NOT NULL
        DEFAULT '00000000-0000-0000-0000-000000000000';

CREATE TABLE common.outbox_messages
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    message_type text NOT NULL,
    schema_version integer NOT NULL,
    producer text NOT NULL,
    payload text NOT NULL,
    correlation_id text NULL,
    status integer NOT NULL,
    published_at timestamp with time zone NULL,
    attempt_count integer NOT NULL,
    last_attempt_at timestamp with time zone NULL,
    next_attempt_at timestamp with time zone NULL,
    last_error text NULL
);

CREATE UNIQUE INDEX ix_outbox_messages_external_id ON common.outbox_messages (external_id);
CREATE INDEX ix_outbox_messages_status_next_attempt_at
    ON common.outbox_messages (status, next_attempt_at);
