CREATE SCHEMA IF NOT EXISTS common;
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE common.email_messages
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    subject text NOT NULL,
    body_html text NOT NULL,
    recipient text NOT NULL,
    sent boolean NOT NULL,
    sent_at timestamp with time zone NULL
);

CREATE TABLE common.error_logs
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    source text NOT NULL,
    exception_type text NOT NULL,
    message text NOT NULL,
    stack_trace text NULL,
    request_path text NULL,
    trace_id text NULL
);

CREATE TABLE auth.token_types
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    name text NOT NULL
);

CREATE TABLE auth.users
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    login text NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    email_confirmed boolean NOT NULL,
    password_hash text NOT NULL,
    password_changed_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    failed_login_attempts integer NOT NULL,
    locked_until timestamp with time zone NULL,
    last_login_at timestamp with time zone NULL
);

CREATE TABLE auth.refresh_tokens
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    user_id bigint NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone NULL,
    CONSTRAINT fk_refresh_tokens_users_user_id
        FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

CREATE TABLE auth.tokens
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    token_type_id bigint NOT NULL,
    user_id bigint NOT NULL,
    email_message_id bigint NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    validated boolean NOT NULL,
    validated_at timestamp with time zone NULL,
    CONSTRAINT fk_tokens_token_types_token_type_id
        FOREIGN KEY (token_type_id) REFERENCES auth.token_types (id) ON DELETE CASCADE,
    CONSTRAINT fk_tokens_users_user_id
        FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

INSERT INTO auth.token_types (
    id,
    created_at,
    external_id,
    name,
    updated_at
)
VALUES
    (
        1,
        '2026-08-31 00:00:00+00',
        '00000000-0000-0000-0000-000000000001',
        'UserCreationValidation',
        NULL
    ),
    (
        2,
        '2026-08-31 00:00:00+00',
        '00000000-0000-0000-0000-000000000002',
        'PasswordReset',
        NULL
    );

CREATE UNIQUE INDEX ix_email_messages_external_id ON common.email_messages (external_id);
CREATE UNIQUE INDEX ix_error_logs_external_id ON common.error_logs (external_id);
CREATE UNIQUE INDEX ix_refresh_tokens_external_id ON auth.refresh_tokens (external_id);
CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON auth.refresh_tokens (token_hash);
CREATE INDEX ix_refresh_tokens_user_id ON auth.refresh_tokens (user_id);
CREATE UNIQUE INDEX ix_token_types_external_id ON auth.token_types (external_id);
CREATE UNIQUE INDEX ix_token_types_name ON auth.token_types (name);
CREATE UNIQUE INDEX ix_tokens_external_id ON auth.tokens (external_id);
CREATE UNIQUE INDEX ix_tokens_token_hash ON auth.tokens (token_hash);
CREATE INDEX ix_tokens_token_type_id ON auth.tokens (token_type_id);
CREATE INDEX ix_tokens_user_id ON auth.tokens (user_id);
CREATE UNIQUE INDEX ix_users_email ON auth.users (email);
CREATE UNIQUE INDEX ix_users_external_id ON auth.users (external_id);
CREATE UNIQUE INDEX ix_users_login ON auth.users (login);
