CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS common;

CREATE TABLE notifications.email_deliveries
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    producer text NOT NULL,
    request_id uuid NOT NULL,
    recipient text NOT NULL,
    template_key text NOT NULL,
    template_version integer NOT NULL,
    locale text NOT NULL,
    subject text NOT NULL,
    body_html text NOT NULL,
    content_fingerprint text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    correlation_id text NULL,
    status integer NOT NULL,
    attempt_count integer NOT NULL,
    next_attempt_at timestamp with time zone NULL,
    sent_at timestamp with time zone NULL,
    last_error text NULL
);

CREATE TABLE common.error_logs
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    source text NOT NULL,
    exception_type text NOT NULL,
    message text NOT NULL,
    stack_trace text NULL,
    request_path text NULL,
    trace_id text NULL
);

CREATE TABLE common.outbox_messages
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    message_type text NOT NULL,
    schema_version integer NOT NULL,
    producer text NOT NULL,
    payload text NOT NULL,
    correlation_id text NULL,
    status integer NOT NULL,
    published_at timestamp with time zone NULL,
    attempt_count integer NOT NULL,
    last_attempt_at timestamp with time zone NULL,
    next_attempt_at timestamp with time zone NULL,
    last_error text NULL
);

CREATE TABLE notifications.email_delivery_attempts
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NULL,
    email_delivery_id bigint NOT NULL,
    attempt_number integer NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone NULL,
    succeeded boolean NULL,
    error text NULL,
    CONSTRAINT fk_email_delivery_attempts_email_deliveries_email_delivery_id
        FOREIGN KEY (email_delivery_id)
        REFERENCES notifications.email_deliveries (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_email_deliveries_external_id
    ON notifications.email_deliveries (external_id);
CREATE UNIQUE INDEX ix_email_deliveries_producer_request_id
    ON notifications.email_deliveries (producer, request_id);
CREATE INDEX ix_email_deliveries_status_next_attempt_at
    ON notifications.email_deliveries (status, next_attempt_at);
CREATE UNIQUE INDEX ix_email_delivery_attempts_email_delivery_id_attempt_number
    ON notifications.email_delivery_attempts (email_delivery_id, attempt_number);
CREATE UNIQUE INDEX ix_email_delivery_attempts_external_id
    ON notifications.email_delivery_attempts (external_id);
CREATE UNIQUE INDEX ix_error_logs_external_id
    ON common.error_logs (external_id);
CREATE UNIQUE INDEX ix_outbox_messages_external_id
    ON common.outbox_messages (external_id);
CREATE INDEX ix_outbox_messages_status_next_attempt_at
    ON common.outbox_messages (status, next_attempt_at);
